# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cinema-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cinema-app
  pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

  target 'cinema-app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cinema-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cinema-app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cinema-app-tvOS

  target 'cinema-app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
